name: flutter_bootstrap_aad
description: A partial implementation of Bootstrap Grid system in Flutter for Responsive Layout.
version: 1.0.0-null-safety
homepage: https://github.com/dhorajiaabhishek/flutter_bootstrap_aad

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
